### ISSUE TITLE
 Ordenes de Compras: Como usuario puedo visualizar el total de la orden al eliminar un detalle

### ISSUE THREAD

**Issue by agimenezpy** [pmmrpy/SIGB#1]

**Comment by pmmrpy** [comment]
Solucionado con JavaScript.
Porcion de codigo incorporado en orden_compra.js:

_$('input[type=checkbox]').on('change', function() {
            var suma = 0;
            $('input[type=checkbox]').each(function (key, value) {
                var a = $(value).is(':checked');
                if (a == false) {
                    suma = suma + parseFloat(value.parentElement.parentElement.children[3].children[0].value)
                }
            });
            $('#id_total_orden_compra').val(suma);
        });_
